# Generated by Django 5.1.7 on 2025-05-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volatile_acidity', models.FloatField()),
                ('citric_acid', models.FloatField()),
                ('density', models.FloatField()),
                ('pH', models.FloatField()),
                ('alcohol', models.FloatField()),
                ('residual_sugar', models.FloatField()),
                ('chloride', models.FloatField()),
                ('sulphates', models.FloatField()),
                ('fixed_acidity', models.FloatField()),
                ('free_sulfur_dioxide', models.FloatField()),
                ('total_sulfur_dioxide', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
